#!/bin/bash

if [ -z "$_ORB_LOCAL_INVOKE" ]; then
    _orb_bash_completion () {
        local tasks=()

        __orb_complete_tasks() {
            local task_path
            while IFS= read -r; do
                task_path=$(basename "$REPLY")
                tasks+=("${task_path%.*}")
            done < <(orb --list)
        }

        __orb_complete_next_task() {
            local task_basename task_completion \
                  task_dir task_name=$1 task_path

            task_path=$(orb --list "$task_name" | tr '\0' '\n')
            [[ -z $task_path ]] && return 0
            (( $(wc -l <<< "$task_path") > 1 )) && return 0

            task_path="$(realpath "$task_path")"
            task_dir="$(dirname "$task_path")"
            task_basename="$(basename "${task_path}")"
            task_completion="${task_basename%.*}.orb_bash_completion"

            if [ -f "${task_dir}/${task_completion}" ]; then
                eval "$(orb --env)"
                # shellcheck disable=SC1090
                _ORB_BASH_COMPLETION=1 source "${task_dir}/${task_completion}" && \
                _exec_orb_bash_completion; \
                unset _exec_orb_bash_completion
            fi

            return 0
        }

        if [ "${COMP_CWORD}" -eq "1" ]; then
            __orb_complete_tasks
            # shellcheck disable=SC2207
            COMPREPLY=($(compgen -W "$(printf -- '%q ' "${tasks[@]}")" -- "${COMP_WORDS[1]}"))
        elif [ "${COMP_CWORD}" -gt "1" ]; then
            __orb_complete_next_task "${COMP_WORDS[1]}"
        fi

        return 0
    }

    complete -F _orb_bash_completion orb
fi
